bins = ["boot.bin", "init0.bin"]
srcs = bins.map {|f| f.gsub(".bin", ".asm") }

(0...bins.size).each do |i|
    file bins[i] => srcs[i] do |t|
        sh "nasm -f bin #{srcs[i]} -o #{bins[i]}"
    end
end

task :build do |t|
    bins.each {|bin| Rake::Task[bin].invoke}
end

task :clean do |t|
    sh "del *.bin"
end
